### ISSUE TITLE
Softwrap fix which is enabled by default prevent <num>j/k motions

### ISSUE THREAD

**Issue by akinsho** [jghauser/fold-cycle.nvim#2]
Hi 👋🏾,

I've really enjoyed using `fold-cycle` before and was glad to see a nvim geared version of it. I've been using it happily for a while until today I just noticed that I couldn't do `10j/k` jumps etc. (not specifically 10). On investigating I found that this plugin swallows my `j/k` key and prevents this native movement. I think probably this plugin shouldn't automatically map j/k since those are core keys and if it does, it should be very explicit in the README, even more so than it is. I did see the notice but somehow didn't think it would mean this.

**Comment by jghauser** [comment]
Hey! Yeah, that's a good point! I wrote this program because of my own needs and the default settings are basically simply what I use. I thought this wouldn't have any adverse consequences -- but that's clearly not the case. I'll fix the bug in the next days, and I think I'll make that setting default to off. Thanks again!
