### ISSUE TITLE
folding not working all of a sudden

### ISSUE THREAD

**Issue by nibudd** [jghauser/fold-cycle.nvim#7]
I installed fold-cycle a few days ago. It was working fine when I installed it. I've probably installed one or two more plugins since then. I can't recall if I've used the folding feature between then and today when I discovered it is no longer working. I've looked through my keymaps `:map` to make sure my keymaps haven't been overwritten. I haven't done much troubleshooting on nvim plugins before, so I'm not sure what else I can provide that would be helpful right now. Happy to help track down what anyone might need to duplicate the issue

**Comment by nibudd** [comment]
I've also tried uninstalling and reinstalling the plugin (I use Lazy). I uninstalled by renaming the lua file holding the plugin's config, running Lazy's clean command, then restoring the filename and installing fresh

**Comment by nibudd** [comment]
one more update. the plugins I installed after fold-cycle were treesitter-context and todo-comments. I've uninstalled both, uninstalled fold-cycle, and then re-installed fold-cycle. still not working properly

**Comment by ESSO0428** [comment]
> I installed fold-cycle a few days ago. It was working fine when I installed it. I've probably installed one or two more plugins since then. I can't recall if I've used the folding feature between then and today when I discovered it is no longer working. I've looked through my keymaps `:map` to make sure my keymaps haven't been overwritten. I haven't done much troubleshooting on nvim plugins before, so I'm not sure what else I can provide that would be helpful right now. Happy to help track down what anyone might need to duplicate the issue

Certainly! Here's the complete message in English:

Hello nibudd,

It seems that you are experiencing some issues with the folding functionality. Sometimes the state of folds can become disrupted, and you can try using the :e! command to forcibly reload the current file, which might help reset the folding state.

Additionally, to ensure that folding is functioning correctly, you should set the following configurations:

```lua
vim.wo.foldlevel = 99
vim.wo.foldenable = true
vim.opt.foldlevelstart = 99
-- Adjust the following settings based on your setup
-- vim.wo.foldmethod = "expr"
-- vim.wo.foldexpr = "nvim_treesitter#foldexpr()"
```

These settings will make sure that folding is enabled and the fold level is set high enough so that files are not folded automatically when opened. If you are using Tree-sitter for folding, ensure that foldmethod and foldexpr are correctly configured.

Lastly, you can test if the fold functions are operating properly by using the `zM` (close all folds) and `zR` (open all folds) commands. Additionally, to verify that the fold toggle function is working correctly, you can use the `za` command. This command toggles the fold at the cursor, allowing you to quickly check if both folding and unfolding actions are functioning as expected. This can be very helpful for diagnosing issues with folding behavior in your configuration.

I hope these steps help you resolve the folding issues. If you have any more questions or need further assistance, feel free to reply or update, and I'm happy to help further.

This comprehensive response should help nibudd troubleshoot and hopefully resolve the folding issues they are encountering in Neovim.

**Comment by jghauser** [comment]
@ESSO0428, thanks a lot for helping @nibudd out! :heart:

**Comment by nibudd** [comment]
Really appreciate your help on this. Unfortunately, these settings have not worked for me. I've included my lazy config for fold-cycle below, including the settings you've suggested. Folding doesn't work in lua or python files.

Also, when trying `zM`, `zR`, and `za` I see a `E490: No fold found` error 😞 

```lua
-- .config/nvim/lua/plugins/fold-cycle.lua
return {
    "jghauser/fold-cycle.nvim",
    config = function()
        local fold_cycle = require("fold-cycle")

        fold_cycle.setup({
            open_if_max_closed = false,    -- closing a fully closed fold will open it
            close_if_max_opened = false,   -- opening a fully open fold will close it
        })

        vim.wo.foldlevel = 99
        vim.wo.foldenable = true
        vim.opt.foldlevelstart = 99
        -- Adjust the following settings based on your setup
        -- vim.wo.foldmethod = "expr"
        -- vim.wo.foldexpr = "nvim_treesitter#foldexpr()"

        vim.keymap.set("n", "<Tab>",
            function() return fold_cycle.close() end,
            {silent = true, desc = "Fold-cycle: close folds"})

        vim.keymap.set("n", "<S-Tab>",
            function() return fold_cycle.open() end,
            {silent = true, desc = "Fold-cycle: open folds"})

        vim.keymap.set("n", "<M-Tab>",
            function() return fold_cycle.toggle_all() end,
            {remap = true, silent = true, desc = "Fold-cycle: toggle all folds"})
    end
}

```

**Comment by ESSO0428** [comment]
Hello @nibudd 

Based on the configuration you've provided, placing global folding settings within a plugin's `config` function might lead to scope issues. Such settings may not be applied correctly during Neovim's initialization process, especially if they depend on the order in which plugins are loaded.

I recommend moving settings like `foldlevel`, `foldenable`, and `foldlevelstart` to `init.lua` or another global configuration file. This ensures that they are set up correctly at Neovim startup, not only ensuring the normal operation of folding functionality but also avoiding problems caused by the loading order of plugins.

Here are some further suggestions that might help resolve the folding problems in Neovim:

1. **Using Tree-sitter for folding:**
   If you have Tree-sitter installed, make sure to install the necessary parsers for Lua and Python with `:TSInstall lua` and `:TSInstall python`. Then, configure Tree-sitter based folding with the following settings:
    ```lua
    vim.wo.foldlevel = 99
    vim.wo.foldenable = true
    vim.wo.foldmethod = "expr"
    vim.wo.foldexpr = "nvim_treesitter#foldexpr()"
    ```
2. **Simple folding using indentation:**
If you prefer a simpler folding method, consider using indentation as the basis for folding:
      ```lua
      vim.wo.foldlevel = 99
      vim.wo.foldenable = true
      vim.wo.foldmethod = "indent"
      ```
      This setup generally solves basic folding needs for most languages.

3. **Using the nvim-ufo plugin:**
If you are considering using the [nvim-ufo](https://github.com/kevinhwang91/nvim-ufo) plugin, configure it as recommended:
    ```lua
    vim.wo.foldlevel = 99
    vim.wo.foldenable = true
    vim.wo.foldmethod = "manual"
    vim.o.foldlevelstart = 99
    ```
---

In addition, you can use the zM and zR commands to close and open all folds respectively. You can also use za at indentations to toggle folds, as shown in the following examples:
In Python:
```python
class MyClass(object): `<- za`

    """Docstring for MyClass. """

    def __init__(self): `<- za`
        """TODO: to be defined. """
 
    def ...
```
In lua:
```lua
lvim.plugins = { `<- za`
  { `<- za`
    "folke/trouble.nvim",
    cmd = "TroubleToggle"
  },
  { "skywind3000/asyncrun.vim" },
  { "kevinhwang91/rnvimr" },
  { `<- za`
    "kevinhwang91/nvim-hlslens",
    config = function()
      require('hlslens').setup({})
    end
  },
...
```
---

Ensure these settings are placed in your init.lua or a similar global configuration file to ensure they are applied at Neovim startup. After making these changes, please restart Neovim.

Upon restarting, you can check if the fold settings are correctly applied by entering the following commands in Neovim:
```vim
:lua=vim.wo.foldmethod
:lua=vim.wo.foldlevel
:lua=vim.wo.foldenable
```

---

If folding does not work as expected, try running :e! to force reload the file, which often fixes issues with settings not being applied correctly.

I hope these suggestions help you resolve the folding issues. If you have any more questions or need further assistance, feel free to reply or reach out.

**Comment by nibudd** [comment]
aha, I use tree-sitter, and with your suggested changes it is working now. I moved the window options up to a config file that gets loaded before any plugins. I wonder why it worked originally but then stopped. Maybe I just got lucky the first time, because I didn't have that many plugins, so the default settings were being loaded early enough?

Anyway, thanks for your help!

**Comment by jghauser** [comment]
great to hear @nibudd, and thanks again @ESSO0428 for providing the support!
